# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import raft_pb2 as raft__pb2


class RaftServiceStub(object):
    """python -m grpc_tools.protoc -I. --python_out=.  --grpc_python_out=. --pyi_out=. raft.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/RaftService/RequestVote',
                request_serializer=raft__pb2.VoteRequest.SerializeToString,
                response_deserializer=raft__pb2.VoteResponse.FromString,
                )
        self.SendLogs = channel.unary_unary(
                '/RaftService/SendLogs',
                request_serializer=raft__pb2.LogRequest.SerializeToString,
                response_deserializer=raft__pb2.LogResponse.FromString,
                )
        self.ServeClient = channel.unary_unary(
                '/RaftService/ServeClient',
                request_serializer=raft__pb2.ClientRequest.SerializeToString,
                response_deserializer=raft__pb2.ClientReply.FromString,
                )
        self.DetermineFollowerAcks = channel.unary_unary(
                '/RaftService/DetermineFollowerAcks',
                request_serializer=raft__pb2.FollowerAckRequest.SerializeToString,
                response_deserializer=raft__pb2.FollowerAckResponse.FromString,
                )


class RaftServiceServicer(object):
    """python -m grpc_tools.protoc -I. --python_out=.  --grpc_python_out=. --pyi_out=. raft.proto
    """

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetermineFollowerAcks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=raft__pb2.VoteRequest.FromString,
                    response_serializer=raft__pb2.VoteResponse.SerializeToString,
            ),
            'SendLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogs,
                    request_deserializer=raft__pb2.LogRequest.FromString,
                    response_serializer=raft__pb2.LogResponse.SerializeToString,
            ),
            'ServeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeClient,
                    request_deserializer=raft__pb2.ClientRequest.FromString,
                    response_serializer=raft__pb2.ClientReply.SerializeToString,
            ),
            'DetermineFollowerAcks': grpc.unary_unary_rpc_method_handler(
                    servicer.DetermineFollowerAcks,
                    request_deserializer=raft__pb2.FollowerAckRequest.FromString,
                    response_serializer=raft__pb2.FollowerAckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """python -m grpc_tools.protoc -I. --python_out=.  --grpc_python_out=. --pyi_out=. raft.proto
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/RequestVote',
            raft__pb2.VoteRequest.SerializeToString,
            raft__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/SendLogs',
            raft__pb2.LogRequest.SerializeToString,
            raft__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/ServeClient',
            raft__pb2.ClientRequest.SerializeToString,
            raft__pb2.ClientReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetermineFollowerAcks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/DetermineFollowerAcks',
            raft__pb2.FollowerAckRequest.SerializeToString,
            raft__pb2.FollowerAckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
